"""empty message

Revision ID: 4f1863082a7b
Revises: 
Create Date: 2023-06-02 13:36:40.526668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1863082a7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name_space', sa.String(length=1024), nullable=False),
    sa.Column('runtime', sa.String(length=128), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Task_name_space'), ['name_space'], unique=False)
        batch_op.create_index(batch_op.f('ix_Task_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Task_title'))
        batch_op.drop_index(batch_op.f('ix_Task_name_space'))

    op.drop_table('Task')
    # ### end Alembic commands ###
